### ISSUE TITLE
Failed to emerge chromeos-base/chrome-icu-96.0.4664.208_rc-r1 for /build/rpi4/, Log file:

### ISSUE THREAD

**Issue by wwd-615** [FydeOS/chromium_os-raspberry_pi#241]
I get the following error when executing./build_packages --board=rpi4 --nowithautotest. Can you help me
>>> 11:21:16 Failed to emerge chromeos-base/chrome-icu-96.0.4664.208_rc-r1 for /build/rpi4/, Log file:
>>> 11:21:16   /build/rpi4/tmp/portage/logs/chromeos-base:chrome-icu-96.0.4664.208_rc-r1:20230329-032107.log
>>> 11:21:16 === Start output for job chrome-icu-96.0.4664.208_rc-r1 ===
chrome-icu-96.0.4664.208_rc-r1:  * Package:    chromeos-base/chrome-icu-96.0.4664.208_rc-r1
chrome-icu-96.0.4664.208_rc-r1:  * Repository: cros-pi
chrome-icu-96.0.4664.208_rc-r1:  * USE:        arm cups elibc_glibc kernel_linux libcxx neon runhooks userland_GNU xkbcommon
chrome-icu-96.0.4664.208_rc-r1:  * FEATURES:   network-sandbox splitdebug userpriv
chrome-icu-96.0.4664.208_rc-r1:  * Running stacked hooks for pre_pkg_setup
chrome-icu-96.0.4664.208_rc-r1:  *    sysroot_build_bin_dir ...
chrome-icu-96.0.4664.208_rc-r1:  [ ok ]
chrome-icu-96.0.4664.208_rc-r1:  * Using python2.7 to build
chrome-icu-96.0.4664.208_rc-r1:  * Running stacked hooks for post_pkg_setup
chrome-icu-96.0.4664.208_rc-r1:  *    python_eclass_hack ...
chrome-icu-96.0.4664.208_rc-r1:  [ ok ]
chrome-icu-96.0.4664.208_rc-r1: 11:21:13 >>> Unpacking source...
chrome-icu-96.0.4664.208_rc-r1:  * CHROME_ORIGIN VALUE is LOCAL_SOURCE
chrome-icu-96.0.4664.208_rc-r1:  * ERROR: chromeos-base/chrome-icu-96.0.4664.208_rc-r1::cros-pi failed (unpack phase):
chrome-icu-96.0.4664.208_rc-r1:  *   /mnt/host/source/fydeos/chromium does not contain a valid chromium checkout!
chrome-icu-96.0.4664.208_rc-r1:  * 
chrome-icu-96.0.4664.208_rc-r1:  * Call stack:
chrome-icu-96.0.4664.208_rc-r1:  *               ebuild.sh, line  125:  Called src_unpack
chrome-icu-96.0.4664.208_rc-r1:  *             environment, line 4455:  Called die
chrome-icu-96.0.4664.208_rc-r1:  * The specific snippet of code:
chrome-icu-96.0.4664.208_rc-r1:  *                   die "${CHROME_ROOT} does not contain a valid chromium checkout!";
chrome-icu-96.0.4664.208_rc-r1:  * 
chrome-icu-96.0.4664.208_rc-r1:  * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chrome-icu-96.0.4664.208_rc-r1:20230329-032107.log
chrome-icu-96.0.4664.208_rc-r1:  * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chrome-icu-96.0.4664.208_rc-r1/temp/build.log
chrome-icu-96.0.4664.208_rc-r1:  * CWD: /build/rpi4/tmp/portage/chromeos-base/chrome-icu-96.0.4664.208_rc-r1/work
chrome-icu-96.0.4664.208_rc-r1:  * S:   /build/rpi4/tmp/portage/chromeos-base/chrome-icu-96.0.4664.208_rc-r1/work/chrome-icu-96.0.4664.208_rc

**Comment by ifttl** [comment]
It looks like you are using the r96-dev branch of the code. Please remove the CHROME_ROOT line from project-cros-pi/make.conf, and then re-run cros_sdk using --chrome-root to point to the directory of the Chromium source code and enter the chroot environment. You may also want to try using the updated r102-dev or r108-dev branches.

**Comment by nirocfz** [comment]
It looks like you are using the r96-dev branch of the code.
Please remove the `CHROME_ROOT` line from project-cros-pi/make.conf, and then re-run `cros_sdk` using `--chrome-root` to point to the directory of the Chromium source code and enter the chroot environment.

You may also want to try using the updated r102-dev or r108-dev branches.

**Comment by wwd-615** [comment]
thank you very much, let me try

**Comment by wwd-615** [comment]
When I changed the make.conf file, I still got the following error，can you help me：

>>> 14:16:10 Failed to emerge chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1 for /build/rpi4/, Log file:
>>> 14:16:10   /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230331-061607.log
>>> 14:16:10 === Start output for job chromeos-chrome-96.0.4664.208_rc-r1 ===
chromeos-chrome-96.0.4664.208_rc-r1:  * Package:    chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1
chromeos-chrome-96.0.4664.208_rc-r1:  * Repository: cros-pi
chromeos-chrome-96.0.4664.208_rc-r1:  * USE:        accessibility afdo_use arm autotest build_tests buildcheck cfi chrome_debug chrome_media chrome_remoting cros-debug debug_fission dwarf5 elibc_glibc fonts highdpi kernel_linux libcxx nacl neon oobe_config opengles orderfile_use ozone_platform_default_gbm ozone_platform_gbm ozone_platform_headless runhooks thinlto userland_GNU xkbcommon
chromeos-chrome-96.0.4664.208_rc-r1:  * FEATURES:   network-sandbox splitdebug userpriv
chromeos-chrome-96.0.4664.208_rc-r1:  * Running stacked hooks for pre_pkg_setup
chromeos-chrome-96.0.4664.208_rc-r1:  *    sysroot_build_bin_dir ...
chromeos-chrome-96.0.4664.208_rc-r1:  [ ok ]
chromeos-chrome-96.0.4664.208_rc-r1:  * Using python2.7 to build
chromeos-chrome-96.0.4664.208_rc-r1:  * Running stacked hooks for post_pkg_setup
chromeos-chrome-96.0.4664.208_rc-r1:  *    python_eclass_hack ...
chromeos-chrome-96.0.4664.208_rc-r1:  [ ok ]
chromeos-chrome-96.0.4664.208_rc-r1: 14:16:09 >>> Unpacking source...
chromeos-chrome-96.0.4664.208_rc-r1: 
chromeos-chrome-96.0.4664.208_rc-r1:  * If you want to develop or hack on the browser itself, you should follow the
chromeos-chrome-96.0.4664.208_rc-r1:  * simple chrome workflow instead of using emerge:
chromeos-chrome-96.0.4664.208_rc-r1:  * https://chromium.googlesource.com/chromiumos/docs/+/master/simple_chrome_workflow.md
chromeos-chrome-96.0.4664.208_rc-r1: 
chromeos-chrome-96.0.4664.208_rc-r1:  * Setting up CrOS credentials
chromeos-chrome-96.0.4664.208_rc-r1: '/home/ubuntu/.ssh' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/homedir/.ssh'
chromeos-chrome-96.0.4664.208_rc-r1: '/home/ubuntu/.ssh/config' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/homedir/.ssh/config'
chromeos-chrome-96.0.4664.208_rc-r1: '/home/ubuntu/.ssh/known_hosts' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/homedir/.ssh/known_hosts'
chromeos-chrome-96.0.4664.208_rc-r1: '/home/ubuntu/.ssh/config.orig' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/homedir/.ssh/config.orig'
chromeos-chrome-96.0.4664.208_rc-r1:  * CHROME_ORIGIN VALUE is LOCAL_SOURCE
chromeos-chrome-96.0.4664.208_rc-r1: Building Chromium with additional media codecs and containers.
chromeos-chrome-96.0.4664.208_rc-r1: 14:16:09 >>> Source unpacked in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work
chromeos-chrome-96.0.4664.208_rc-r1:  * Running stacked hooks for post_src_unpack
chromeos-chrome-96.0.4664.208_rc-r1:  *    asan_init ...
chromeos-chrome-96.0.4664.208_rc-r1:  [ ok ]
chromeos-chrome-96.0.4664.208_rc-r1:  * Running stacked hooks for pre_src_prepare
chromeos-chrome-96.0.4664.208_rc-r1:  *    build_toolchain_catch ...
chromeos-chrome-96.0.4664.208_rc-r1:  [ ok ]
chromeos-chrome-96.0.4664.208_rc-r1:  *    enable_cxx_exceptions ...
chromeos-chrome-96.0.4664.208_rc-r1:  [ ok ]
chromeos-chrome-96.0.4664.208_rc-r1: 14:16:09 >>> Preparing source in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc ...
chromeos-chrome-96.0.4664.208_rc-r1:  * /home/ubuntu/chrome_root should be set here properly
chromeos-chrome-96.0.4664.208_rc-r1: rm: cannot remove 'c': Read-only file system
chromeos-chrome-96.0.4664.208_rc-r1:  * ERROR: chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi failed (prepare phase):
chromeos-chrome-96.0.4664.208_rc-r1:  *   Could not remove symlink
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Call stack:
chromeos-chrome-96.0.4664.208_rc-r1:  *               ebuild.sh, line  125:  Called src_prepare
chromeos-chrome-96.0.4664.208_rc-r1:  *             environment, line 5327:  Called die
chromeos-chrome-96.0.4664.208_rc-r1:  * The specific snippet of code:
chromeos-chrome-96.0.4664.208_rc-r1:  *           rm -rf "${BUILD_OUT_SYM}" || die "Could not remove symlink";
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230331-061607.log
chromeos-chrome-96.0.4664.208_rc-r1:  * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/temp/build.log
chromeos-chrome-96.0.4664.208_rc-r1:  * CWD: /home/ubuntu/chrome_root/src
chromeos-chrome-96.0.4664.208_rc-r1:  * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc
>>> 14:16:12 Installing (1 of 14) chromeos-base/chromeos-ssh-testkeys-0.0.1-r2::chromiumos to /build/rpi4/
>>> 14:16:16 Completed (1 of 14) chromeos-base/chromeos-ssh-testkeys-0.0.1-r2::chromiumos to /build/rpi4/
>>> 14:16:16 Jobs: 1 of 14 complete, 1 failed                Load avg: 1.81, 2.72, 3.16

 * Messages for package chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1 merged to /build/rpi4/:
 * Log file: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230331-061607.log

 * If you want to develop or hack on the browser itself, you should follow the
 * simple chrome workflow instead of using emerge:
 * https://chromium.googlesource.com/chromiumos/docs/+/master/simple_chrome_workflow.md
 * CHROME_ORIGIN VALUE is LOCAL_SOURCE
 * /home/ubuntu/chrome_root should be set here properly
 * ERROR: chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi failed (prepare phase):
 *   Could not remove symlink
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 5327:  Called die
 * The specific snippet of code:
 *           rm -rf "${BUILD_OUT_SYM}" || die "Could not remove symlink";
 * 
 * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230331-061607.log
 * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/temp/build.log
 * CWD: /home/ubuntu/chrome_root/src
 * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc

**Comment by nirocfz** [comment]
It can be seen that within the chroot environment, the current user is unable to modify any content within the chromium source code directory /home/ubuntu/chrome_root/src, resulting in a compilation failure. Please check the ownership and permissions of the source code directory.

**Comment by wwd-615** [comment]
thank you very much

**Comment by wwd-615** [comment]
I have encountered a new problem, can you help me to have a look?
chromeos-chrome-96.0.4664.208_rc-r1: ninja: build stopped: subcommand failed.
chromeos-chrome-96.0.4664.208_rc-r1:  * ERROR: chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi failed (compile phase):
chromeos-chrome-96.0.4664.208_rc-r1:  *   (no error message)
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Call stack:
chromeos-chrome-96.0.4664.208_rc-r1:  *               ebuild.sh, line  125:  Called src_compile
chromeos-chrome-96.0.4664.208_rc-r1:  *             environment, line 5326:  Called chrome_make 'chrome' 'capture_unittests' 'dawn_end2end_tests' 'dawn_unittests' 'gl_tests' 'jpeg_decode_accelerator_unittest' 'ozone_gl_unittests' 'sandbox_linux_unittests' 'wayland_client_perftests' 'ppapi/examples/video_decode' 'bitmaptools' 'clear_system_cache' 'minidump_stackwalk' 'chromedriver' 'nacl_helper_bootstrap' 'nacl_helper'
chromeos-chrome-96.0.4664.208_rc-r1:  *             environment, line 1815:  Called die
chromeos-chrome-96.0.4664.208_rc-r1:  * The specific snippet of code:
chromeos-chrome-96.0.4664.208_rc-r1:  *       [[ "${ret}" -eq 0 ]] || die;
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230402-144551.log
chromeos-chrome-96.0.4664.208_rc-r1:  * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/temp/build.log
chromeos-chrome-96.0.4664.208_rc-r1:  * CWD: /home/wwd/chrome_root/src
chromeos-chrome-96.0.4664.208_rc-r1:  * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc

**Comment by nirocfz** [comment]
The common cause of error is forgetting to execute `gclient sync` in the Chromium source code root directory. Please try executing `gclient sync` and `emerge` it again.

**Comment by wwd-615** [comment]
Ok, thank you very much. I'll try it

**Comment by wwd-615** [comment]
I executed the gclient sync command, but still got the following error：
chromeos-chrome-96.0.4664.208_rc-r1: ninja: build stopped: subcommand failed.
chromeos-chrome-96.0.4664.208_rc-r1:  * ERROR: chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi failed (compile phase):
chromeos-chrome-96.0.4664.208_rc-r1:  *   (no error message)
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Call stack:
chromeos-chrome-96.0.4664.208_rc-r1:  *               ebuild.sh, line  125:  Called src_compile
chromeos-chrome-96.0.4664.208_rc-r1:  *             environment, line 5326:  Called chrome_make 'chrome' 'capture_unittests' 'dawn_end2end_tests' 'dawn_unittests' 'gl_tests' 'jpeg_decode_accelerator_unittest' 'ozone_gl_unittests' 'sandbox_linux_unittests' 'wayland_client_perftests' 'ppapi/examples/video_decode' 'bitmaptools' 'clear_system_cache' 'minidump_stackwalk' 'chromedriver' 'nacl_helper_bootstrap' 'nacl_helper'
chromeos-chrome-96.0.4664.208_rc-r1:  *             environment, line 1815:  Called die
chromeos-chrome-96.0.4664.208_rc-r1:  * The specific snippet of code:
chromeos-chrome-96.0.4664.208_rc-r1:  *       [[ "${ret}" -eq 0 ]] || die;
chromeos-chrome-96.0.4664.208_rc-r1:  * 
chromeos-chrome-96.0.4664.208_rc-r1:  * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230403-005955.log
chromeos-chrome-96.0.4664.208_rc-r1:  * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/temp/build.log
chromeos-chrome-96.0.4664.208_rc-r1:  * CWD: /home/wwd/chrome_root/src
chromeos-chrome-96.0.4664.208_rc-r1:  * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc
>>> 09:09:03 Jobs: 1 of 14 complete, 1 failed                Load avg: 14.9, 13.9, 7.1

 * Messages for package chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1 merged to /build/rpi4/:
 * Log file: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230403-005955.log

 * If you want to develop or hack on the browser itself, you should follow the
 * simple chrome workflow instead of using emerge:
 * https://chromium.googlesource.com/chromiumos/docs/+/master/simple_chrome_workflow.md
 * CHROME_ORIGIN VALUE is LOCAL_SOURCE
 * /home/wwd/chrome_root should be set here properly
 * ERROR: chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_compile
 *             environment, line 5326:  Called chrome_make 'chrome' 'capture_unittests' 'dawn_end2end_tests' 'dawn_unittests' 'gl_tests' 'jpeg_decode_accelerator_unittest' 'ozone_gl_unittests' 'sandbox_linux_unittests' 'wayland_client_perftests' 'ppapi/examples/video_decode' 'bitmaptools' 'clear_system_cache' 'minidump_stackwalk' 'chromedriver' 'nacl_helper_bootstrap' 'nacl_helper'
 *             environment, line 1815:  Called die
 * The specific snippet of code:
 *       [[ "${ret}" -eq 0 ]] || die;
 * 
 * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-96.0.4664.208_rc-r1:20230403-005955.log
 * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/temp/build.log
 * CWD: /home/wwd/chrome_root/src
 * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1/work/chromeos-chrome-96.0.4664.208_rc

**Comment by wwd-615** [comment]
My build environment is ubuntu18 and the python version is Python 3.8. 0. The python version in cros_sdk is python3.6.12，Is the above error related to the python version?

**Comment by nirocfz** [comment]
I have not encountered such a problem before, and I don't think it's related to the python version. Please go back to the previous steps to ensure that each step is correct, maybe you should try to start over again.

**Comment by wwd-615** [comment]
I have a question, can you help me to answer it？
In the branch r96-dev, "Git clone https://github.com/fydeos/chromium_os-raspberry_pi.git." whether you need this command to "git clone - b r96-dev https://github.com/fydeos/chromium_os-raspberry_pi.git "?

**Comment by fydeos-alpha** [comment]
> I have a question, can you help me to answer it？ In the branch r96-dev, "Git clone https://github.com/fydeos/chromium_os-raspberry_pi.git." whether you need this command to "git clone - b r96-dev https://github.com/fydeos/chromium_os-raspberry_pi.git "?

If you want to specify a branch in the git clone command, yes, you do need `-b` flag to tell git, otherwise it will default to the `main` branch. This is a basic git usage question, and it is beyond this project's scope. You need to familiarise yourself with the basics before attempting to do advanced stuff, like building Chromium OS.

As @nirocfz mentioned above, you have been using an old branch of this project, which was no longer in maintenance for quite some time. I also suggest you start over with r102-dev or r108-dev, which we released not long ago. Also, your build environment ubuntu 1804 is also quite dated, I would upgrade that as well.

**Comment by wwd-615** [comment]
> If you want to specify a branch in the git clone command, yes, you do need `-b` flag to tell git, otherwise it will default to the `main` branch. This is a basic git usage question, and it is beyond this project's scope. You need to familiarise yourself with the basics before attempting to do advanced stuff, like building Chromium OS.

Thank you very much for your advice
Maybe I have a problem expressing myself，What I mean is that whichever branch corresponds to the README document uses the command "git clone https://github.com/fydeos/chromium_os-raspberry_pi.git .". Does the overlays of the main branch work with all versions of chromium os?

**Comment by fydeos-alpha** [comment]
We don't know if the main branch of this project would work on all versions of the Chromium OS platform. At this point in time, the main branch is the bleeding edge branch we are using to submit new code for new features, and we are testing it with Chromium OS r108. If you want to use the main branch, then it's recommended to use Chromium OS [repo](https://chromium.googlesource.com/chromiumos/manifest.git/+/refs/heads/release-R108-15183.B) to match it.

**Comment by wwd-615** [comment]
When I switch to the r102-dev branch, the following error still occurs, and I'm sure I executed the gclinet sync command

>>> 13:35:50 Failed to emerge chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1 for /build/rpi4/, Log file:
>>> 13:35:50   /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-102.0.5005.179_rc-r1:20230406-052617.log
>>> 13:35:50 === Start output for job chromeos-chrome-102.0.5005.179_rc-r1 ===
chromeos-chrome-102.0.5005.179_rc-r1:  * Package:    chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1
chromeos-chrome-102.0.5005.179_rc-r1:  * Repository: cros-pi
chromeos-chrome-102.0.5005.179_rc-r1:  * USE:        accessibility afdo_use arm autotest build_tests buildcheck cfi chrome_debug chrome_media chrome_remoting cros-debug debug_fission dwarf5 elibc_glibc fonts highdpi kernel_linux libcxx nacl neon oobe_config opengles orderfile_use ozone_platform_default_gbm ozone_platform_gbm ozone_platform_headless runhooks thinlto userland_GNU xkbcommon
chromeos-chrome-102.0.5005.179_rc-r1:  * FEATURES:   network-sandbox splitdebug userpriv
chromeos-chrome-102.0.5005.179_rc-r1:  * Running stacked hooks for pre_pkg_setup
chromeos-chrome-102.0.5005.179_rc-r1:  *    sysroot_build_bin_dir ...
chromeos-chrome-102.0.5005.179_rc-r1:  [ ok ]
chromeos-chrome-102.0.5005.179_rc-r1:  * Using python3.6 to build
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:18 >>> Unpacking source...
chromeos-chrome-102.0.5005.179_rc-r1: 
chromeos-chrome-102.0.5005.179_rc-r1:  * If you want to develop or hack on the browser itself, you should follow the
chromeos-chrome-102.0.5005.179_rc-r1:  * simple chrome workflow instead of using emerge:
chromeos-chrome-102.0.5005.179_rc-r1:  * https://chromium.googlesource.com/chromiumos/docs/+/HEAD/simple_chrome_workflow.md
chromeos-chrome-102.0.5005.179_rc-r1:  * 
chromeos-chrome-102.0.5005.179_rc-r1:  * Otherwise, if you have a Chrome checkout already present on your machine, you can
chromeos-chrome-102.0.5005.179_rc-r1:  * re-enter the cros_sdk with the --chrome-root arg and set CHROME_ORIGIN to
chromeos-chrome-102.0.5005.179_rc-r1:  * LOCAL_SOURCE. This will bypass the lengthy sync_chrome phase here.
chromeos-chrome-102.0.5005.179_rc-r1:  * Note: when using --chrome-root, the ebuild won't update or modify the Chrome checkout.
chromeos-chrome-102.0.5005.179_rc-r1:  * So make sure it's at a compatible Chrome version before proceeding.
chromeos-chrome-102.0.5005.179_rc-r1: 
chromeos-chrome-102.0.5005.179_rc-r1:  * Setting up CrOS credentials
chromeos-chrome-102.0.5005.179_rc-r1: '/home/wwd/.ssh' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/homedir/.ssh'
chromeos-chrome-102.0.5005.179_rc-r1: '/home/wwd/.ssh/config' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/homedir/.ssh/config'
chromeos-chrome-102.0.5005.179_rc-r1: '/home/wwd/.ssh/known_hosts' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/homedir/.ssh/known_hosts'
chromeos-chrome-102.0.5005.179_rc-r1: '/home/wwd/.ssh/config.orig' -> '/build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/homedir/.ssh/config.orig'
chromeos-chrome-102.0.5005.179_rc-r1:  * CHROME_ORIGIN VALUE is LOCAL_SOURCE
chromeos-chrome-102.0.5005.179_rc-r1: Building Chromium with additional media codecs and containers.
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:18 >>> Source unpacked in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/work
chromeos-chrome-102.0.5005.179_rc-r1:  * Running stacked hooks for post_src_unpack
chromeos-chrome-102.0.5005.179_rc-r1:  *    asan_init ...
chromeos-chrome-102.0.5005.179_rc-r1:  [ ok ]
chromeos-chrome-102.0.5005.179_rc-r1:  * Running stacked hooks for pre_src_prepare
chromeos-chrome-102.0.5005.179_rc-r1:  *    build_toolchain_catch ...
chromeos-chrome-102.0.5005.179_rc-r1:  [ ok ]
chromeos-chrome-102.0.5005.179_rc-r1:  *    enable_cxx_exceptions ...
chromeos-chrome-102.0.5005.179_rc-r1:  [ ok ]
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:18 >>> Preparing source in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/work/chromeos-chrome-102.0.5005.179_rc ...
chromeos-chrome-102.0.5005.179_rc-r1:  * /home/wwd/chrome_root should be set here properly
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:18 >>> Source prepared.
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:18 >>> Configuring source in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/work/chromeos-chrome-102.0.5005.179_rc ...
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:19  * Appending a library link instruction (-lmmal); libraries to link to should not be passed through LDFLAGS
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:19  * Appending a library link instruction (-lmmal_core); libraries to link to should not be passed through LDFLAGS
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:19  * Appending a library link instruction (-lmmal_util); libraries to link to should not be passed through LDFLAGS
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:19  * Appending a library link instruction (-lmmal_vc_client); libraries to link to should not be passed through LDFLAGS
chromeos-chrome-102.0.5005.179_rc-r1: 13:26:19  * Appending a library link instruction (-lbcm_host); libraries to link to should not be passed through LDFLAGS
chromeos-chrome-102.0.5005.179_rc-r1:  * Building with the compiler settings:
chromeos-chrome-102.0.5005.179_rc-r1:  *   CFLAGS = -pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -faddrsig -Wno-unknown-warning-option
chromeos-chrome-102.0.5005.179_rc-r1:  *   CXXFLAGS = -pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -D__google_stl_debug_vector=1 -faddrsig -Wno-unknown-warning-option -stdlib=libc++
chromeos-chrome-102.0.5005.179_rc-r1:  *   CPPFLAGS = 
chromeos-chrome-102.0.5005.179_rc-r1:  *   LDFLAGS = -Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,-mllvm -Wl,-generate-type-units -stdlib=libc++ -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -Wl,--no-fatal-warnings
chromeos-chrome-102.0.5005.179_rc-r1: /mnt/host/depot_tools/gclient.py runhooks --force
chromeos-chrome-102.0.5005.179_rc-r1: Hook 'vpython -vpython-spec src/.vpython -vpython-tool install' took 39.16 secs
Hook 'vpython3 -vpython-spec src/.vpython3 -vpython-tool install' took 53.89 secs
Running hooks: 100% (131/131), done.: 
chromeos-chrome-102.0.5005.179_rc-r1:  * GN_ARGS = is_chromeos_device=true is_official_build=true is_debug=false  enable_pseudolocales=true use_arc_protected_media=false use_chromeos_protected_av1=false use_chromeos_protected_media=false use_iioservice=false use_v4l2_codec=false use_v4lplugin=false use_vaapi=false use_xkbcommon=true enable_remoting=true enable_nacl=true enable_hibernate=false is_cfm=false is_asan=false is_msan=false is_ubsan=false is_clang=true use_thin_lto=true use_goma_thin_lto=false is_cfi=true use_dwarf5=true enable_assistant_integration_tests=false clang_emit_debug_info_for_profiling=true use_libinput=false nss_slots_software_fallback=false is_chromeos_with_hw_details=false ozone_auto_platforms=false ozone_platform_gbm=true ozone_platform_headless=true use_system_minigbm=true use_system_libdrm=true subpixel_font_rendering_disabled=true arm_use_neon=true blink_symbol_level=1 proprietary_codecs=true use_debug_fission=true symbol_level=2 dcheck_always_on=false clang_use_default_sample_profile=true target_sysroot="/build/rpi4" system_libdir="lib" pkg_config="/build/rpi4/build/bin/pkg-config" target_os="chromeos" host_pkg_config="x86_64-pc-linux-gnu-pkg-config" clang_diagnostic_dir="/tmp/clang_crash_diagnostics" ozone_platform="gbm" target_cpu="arm" arm_float_abi="hard" arm_arch="armv8-a+crc" ffmpeg_branding="ChromeOS" chromeos_afdo_platform="atom" google_api_key="=" google_default_client_id="=" google_default_client_secret="=" cros_target_ar="llvm-ar" cros_target_cc="armv7a-cros-linux-gnueabihf-clang" cros_target_cxx="armv7a-cros-linux-gnueabihf-clang++" host_toolchain="//build/toolchain/cros:host" custom_toolchain="//build/toolchain/cros:target" v8_snapshot_toolchain="//build/toolchain/cros:v8_snapshot" cros_target_ld="armv7a-cros-linux-gnueabihf-clang++" cros_target_nm="llvm-nm" cros_target_readelf="llvm-readelf" cros_target_extra_cflags="-pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -faddrsig -Wno-unknown-warning-option " cros_target_extra_cppflags="" cros_target_extra_cxxflags="-pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -D__google_stl_debug_vector=1 -faddrsig -Wno-unknown-warning-option -stdlib=libc++ " cros_target_extra_ldflags="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,-mllvm -Wl,-generate-type-units -stdlib=libc++ -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -Wl,--no-fatal-warnings " cros_host_cc="x86_64-pc-linux-gnu-clang -B/usr/bin" cros_host_cxx="x86_64-pc-linux-gnu-clang++ -B/usr/bin" cros_host_ar="llvm-ar" cros_host_ld="x86_64-pc-linux-gnu-clang++" cros_host_nm="llvm-nm" cros_host_readelf="llvm-readelf" cros_host_extra_cflags=" -Wno-unknown-warning-option" cros_host_extra_cxxflags=" -Wno-unknown-warning-option" cros_host_extra_cppflags="" cros_host_extra_ldflags=" --unwindlib=libgcc" cros_v8_snapshot_cc="x86_64-pc-linux-gnu-clang -B/usr/bin" cros_v8_snapshot_cxx="x86_64-pc-linux-gnu-clang++ -B/usr/bin" cros_v8_snapshot_ar="llvm-ar" cros_v8_snapshot_ld="x86_64-pc-linux-gnu-clang++" cros_v8_snapshot_nm="llvm-nm" cros_v8_snapshot_readelf="llvm-readelf" cros_v8_snapshot_extra_cflags=" -Wno-unknown-warning-option" cros_v8_snapshot_extra_cxxflags=" -Wno-unknown-warning-option" cros_v8_snapshot_extra_cppflags="" cros_v8_snapshot_extra_ldflags=" --unwindlib=libgcc"
chromeos-chrome-102.0.5005.179_rc-r1: /home/wwd/chrome_root/src/buildtools/linux64/gn gen /home/wwd/chrome_root/src/c/Release --args=is_chromeos_device=true is_official_build=true is_debug=false  enable_pseudolocales=true use_arc_protected_media=false use_chromeos_protected_av1=false use_chromeos_protected_media=false use_iioservice=false use_v4l2_codec=false use_v4lplugin=false use_vaapi=false use_xkbcommon=true enable_remoting=true enable_nacl=true enable_hibernate=false is_cfm=false is_asan=false is_msan=false is_ubsan=false is_clang=true use_thin_lto=true use_goma_thin_lto=false is_cfi=true use_dwarf5=true enable_assistant_integration_tests=false clang_emit_debug_info_for_profiling=true use_libinput=false nss_slots_software_fallback=false is_chromeos_with_hw_details=false ozone_auto_platforms=false ozone_platform_gbm=true ozone_platform_headless=true use_system_minigbm=true use_system_libdrm=true subpixel_font_rendering_disabled=true arm_use_neon=true blink_symbol_level=1 proprietary_codecs=true use_debug_fission=true symbol_level=2 dcheck_always_on=false clang_use_default_sample_profile=true target_sysroot="/build/rpi4" system_libdir="lib" pkg_config="/build/rpi4/build/bin/pkg-config" target_os="chromeos" host_pkg_config="x86_64-pc-linux-gnu-pkg-config" clang_diagnostic_dir="/tmp/clang_crash_diagnostics" ozone_platform="gbm" target_cpu="arm" arm_float_abi="hard" arm_arch="armv8-a+crc" ffmpeg_branding="ChromeOS" chromeos_afdo_platform="atom" google_api_key="=" google_default_client_id="=" google_default_client_secret="=" cros_target_ar="llvm-ar" cros_target_cc="armv7a-cros-linux-gnueabihf-clang" cros_target_cxx="armv7a-cros-linux-gnueabihf-clang++" host_toolchain="//build/toolchain/cros:host" custom_toolchain="//build/toolchain/cros:target" v8_snapshot_toolchain="//build/toolchain/cros:v8_snapshot" cros_target_ld="armv7a-cros-linux-gnueabihf-clang++" cros_target_nm="llvm-nm" cros_target_readelf="llvm-readelf" cros_target_extra_cflags="-pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -faddrsig -Wno-unknown-warning-option " cros_target_extra_cppflags="" cros_target_extra_cxxflags="-pipe -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ffunction-sections -fdata-sections -fno-split-dwarf-inlining -D__google_stl_debug_vector=1 -faddrsig -Wno-unknown-warning-option -stdlib=libc++ " cros_target_extra_ldflags="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,-mllvm -Wl,-generate-type-units -stdlib=libc++ -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -Wl,--no-fatal-warnings " cros_host_cc="x86_64-pc-linux-gnu-clang -B/usr/bin" cros_host_cxx="x86_64-pc-linux-gnu-clang++ -B/usr/bin" cros_host_ar="llvm-ar" cros_host_ld="x86_64-pc-linux-gnu-clang++" cros_host_nm="llvm-nm" cros_host_readelf="llvm-readelf" cros_host_extra_cflags=" -Wno-unknown-warning-option" cros_host_extra_cxxflags=" -Wno-unknown-warning-option" cros_host_extra_cppflags="" cros_host_extra_ldflags=" --unwindlib=libgcc" cros_v8_snapshot_cc="x86_64-pc-linux-gnu-clang -B/usr/bin" cros_v8_snapshot_cxx="x86_64-pc-linux-gnu-clang++ -B/usr/bin" cros_v8_snapshot_ar="llvm-ar" cros_v8_snapshot_ld="x86_64-pc-linux-gnu-clang++" cros_v8_snapshot_nm="llvm-nm" cros_v8_snapshot_readelf="llvm-readelf" cros_v8_snapshot_extra_cflags=" -Wno-unknown-warning-option" cros_v8_snapshot_extra_cxxflags=" -Wno-unknown-warning-option" cros_v8_snapshot_extra_cppflags="" cros_v8_snapshot_extra_ldflags=" --unwindlib=libgcc" --root=/home/wwd/chrome_root/src
chromeos-chrome-102.0.5005.179_rc-r1: Done. Made 24616 targets from 3644 files in 10604ms
chromeos-chrome-102.0.5005.179_rc-r1: 13:28:17 >>> Source configured.
chromeos-chrome-102.0.5005.179_rc-r1: 13:28:18 >>> Compiling source in /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/work/chromeos-chrome-102.0.5005.179_rc ...
chromeos-chrome-102.0.5005.179_rc-r1: ninja: Entering directory `c/Release'
[2/2] LINK ./chrome
chromeos-chrome-102.0.5005.179_rc-r1: FAILED: chrome 
chromeos-chrome-102.0.5005.179_rc-r1: python3 "../../../../../../../home/wwd/chrome_root/src/build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- armv7a-cros-linux-gnueabihf-clang++ -L/var/cache/chromeos-chrome/chrome-src/src/out_rpi4/Release -Werror -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=20 -fwhole-program-vtables -march=armv8-a+crc -Wl,--no-call-graph-profile-sort --target=arm-linux-gnueabihf -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -gsplit-dwarf -Wl,--gdb-index -Wl,-z,defs -Wl,--as-needed --sysroot=../../../../../../../build/rpi4 --rtlib=compiler-rt --unwindlib=libunwind -fsanitize=cfi-vcall -fsanitize=cfi-derived-cast -fsanitize=cfi-unrelated-cast -pie -Wl,--disable-new-dtags -Wl,--lto-O2 -Wl,--symbol-ordering-file -Wl,../../../../../../../home/wwd/chrome_root/src/chromeos/profiles/chromeos.orderfile.txt -Wl,--no-warn-symbol-ordering -Wl,-rpath=\$ORIGIN -L/build/rpi4/usr/lib -Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,-mllvm -Wl,-generate-type-units -stdlib=libc++ -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -Wl,--no-fatal-warnings  -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,--end-group  -ldl -lpthread -lrt -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lcups -lexpat -lfontconfig -ldrm -lsync -lresolv -lxkbcommon -lgbm -levdev-cros -lgestures -lpci -lasound -lcras -lm -lz -ldbus-1 -lffi
chromeos-chrome-102.0.5005.179_rc-r1: clang++: error: unable to execute command: Killed
chromeos-chrome-102.0.5005.179_rc-r1: clang++: error: linker command failed due to signal (use -v to see invocation)
chromeos-chrome-102.0.5005.179_rc-r1: ninja: build stopped: subcommand failed.
chromeos-chrome-102.0.5005.179_rc-r1:  * ERROR: chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1::cros-pi failed (compile phase):
chromeos-chrome-102.0.5005.179_rc-r1:  *   (no error message)
chromeos-chrome-102.0.5005.179_rc-r1:  * 
chromeos-chrome-102.0.5005.179_rc-r1:  * Call stack:
chromeos-chrome-102.0.5005.179_rc-r1:  *               ebuild.sh, line  125:  Called src_compile
chromeos-chrome-102.0.5005.179_rc-r1:  *             environment, line 5353:  Called chrome_make 'chrome' 'capture_unittests' 'dawn_end2end_tests' 'dawn_unittests' 'gl_tests' 'jpeg_decode_accelerator_unittest' 'ozone_gl_unittests' 'sandbox_linux_unittests' 'wayland_client_integration_tests' 'wayland_client_perftests' 'ppapi/examples/video_decode' 'bitmaptools' 'clear_system_cache' 'minidump_stackwalk' 'chromedriver' 'nacl_helper_bootstrap' 'nacl_helper'
chromeos-chrome-102.0.5005.179_rc-r1:  *             environment, line 1840:  Called die
chromeos-chrome-102.0.5005.179_rc-r1:  * The specific snippet of code:
chromeos-chrome-102.0.5005.179_rc-r1:  *       [[ "${ret}" -eq 0 ]] || die;
chromeos-chrome-102.0.5005.179_rc-r1:  * 
chromeos-chrome-102.0.5005.179_rc-r1:  * Build log: /build/rpi4/tmp/portage/logs/chromeos-base:chromeos-chrome-102.0.5005.179_rc-r1:20230406-052617.log
chromeos-chrome-102.0.5005.179_rc-r1:  * Stable log symlink: /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/temp/build.log
chromeos-chrome-102.0.5005.179_rc-r1:  * CWD: /home/wwd/chrome_root/src
chromeos-chrome-102.0.5005.179_rc-r1:  * S:   /build/rpi4/tmp/portage/chromeos-base/chromeos-chrome-102.0.5005.179_rc-r1/work/chromeos-chrome-102.0.5005.179_rc
>>> 13:35:50 Jobs: 4 of 12 complete, 1 failed                Load avg: 2.24, 1.66, 1.40

**Comment by nirocfz** [comment]
It is possible that the compilation process was terminated due to insufficient system resources. You can try to find out if there is any relevant information when the error occurs by looking in `/var/log/messages` (or perhaps `/var/log/syslog`).

**Comment by wwd-615** [comment]
Thank you very much, I tried to give the virtual machine more memory. Another question I would like to ask you is whether you can directly use chromiumos system without chromium compilation

**Comment by wwd-615** [comment]
Due to memory problems on my computer, I want not building  copy of Chromium, How to operate, can help me?

**Comment by wwd-615** [comment]
thank you very much.
